#!/usr/bin/env bash
set -euo pipefail

if [ "${1:-}" = "" ]; then
  cmd="bash"
else
  cmd="$*"
fi

if [ "$(docker ps --filter name=lnx --format="{{.Names}}")" = "" ]; then
  docker run -d --name lnx -h lnx --volume "$HOME:/$HOME" lnx tail -f /dev/null >/dev/null
fi

docker exec -it --privileged -w "/$(pwd)" -e "HOME=$HOME" lnx $cmd
