#!/usr/bin/env bash
set -euo pipefail

if [ "${1:-}" = "" ]; then
  cmd="bash"
else
  cmd="$*"
fi

if [ "$(docker ps --filter name=lnx --format="{{.Names}}")" = "" ]; then
  docker run \
    -d \
    --publish-all \
    --name lnx -h lnx \
    --volume "$HOME:/$HOME" \
    --volume /var/run/docker.sock:/var/run/docker.sock \
    lnx \
    tail -f /dev/null > /dev/null
fi

docker exec -it --privileged -w "/$(pwd)" -e "HOME=$HOME" lnx $cmd
